# These are supported funding model platforms (GitHub sponsors is a funded platform).
github: [atanor-org]
# Uncomment and add your own pages below if you want to accept funding elsewhere.
# custom: ["https://example.com/sponsor"]